api:
  name: "qr-acccounts-sys"
  id: "16181875"
  version: "v1"
  
http:
  path: "/${api.version}/*"
  timeout: "5000" 
  port: "8081"
  private:
    port: "8091"

sfdc:
  username: "aoberrauter-internal@mulesoft.com"
  password: "![stcrDSKORwIIT6orUXx17g==]"
  token: "![iPTdmaHLaaFz42Dr3SHkYlTaoTETFRvbOfvIyoACJV0=]"